# default_project: "0820_183554"
# default_project: "0904_202438"
# default_project: "0919_003836"
default_project: ""
# default_project: "0916_173555"
# default_project: ""
preset_dir: "static/presets"
output_dir: "static/tmp"
save_dir: "static/projects"
